# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d303648abbbf82b09887654b3837f6f3c196a62ed7a52a299a76c17ab39acbf136ba01c7d9ac77bdaa162bf89a376decacdb21cc64460b18f468cd1e4c6f5878

test:
  secret_key_base: 15f382ff03a432dc54a55a51850cae05b3c305f5fd2f287736cd6dd663439dcf45df03e61668cc7cd21d9fc600c275c5c1965dcd4bfd5f1bed4153c88e6f6db3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
